//
//  Table3CeldasProtocols.swift
//  5857Examen iOS
//
//  Created Gerardo on 19/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol Table3CeldasWireframeProtocol: AnyObject {
    func navigatePreguntas()
}
//MARK: Presenter -
protocol Table3CeldasPresenterProtocol: AnyObject {
    func navigatePreguntas()
}

//MARK: Interactor -
protocol Table3CeldasInteractorProtocol: AnyObject {

  var presenter: Table3CeldasPresenterProtocol?  { get set }
}
//MARK: View -
protocol Table3CeldasViewProtocol: AnyObject {

  var presenter: Table3CeldasPresenterProtocol?  { get set }
    
}
