//
//  Table3CeldasViewController.swift
//  5857Examen iOS
//
//  Created Gerardo on 19/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Table3CeldasViewController: UIViewController, Table3CeldasViewProtocol, UINavigationControllerDelegate {

	var presenter: Table3CeldasPresenterProtocol?
    

    @IBOutlet weak var TableExam: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        TableExam.delegate = self
        TableExam.dataSource = self
        TableExam.register(UINib(nibName: "Cell1", bundle: nil), forCellReuseIdentifier: "Cell1")
        TableExam.register(UINib(nibName: "Cell2", bundle: nil), forCellReuseIdentifier: "Cell2")
        TableExam.register(UINib(nibName: "Cell3", bundle: nil), forCellReuseIdentifier: "Cell3")
        TableExam.register(UINib(nibName: "Cell4", bundle: nil), forCellReuseIdentifier: "Cell4")
        TableExam.reloadData()
        
    }
}
extension Table3CeldasViewController: UITableViewDelegate, UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 3
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        switch section{
        case 0:
            return 1
        case 2:
            return 1
        case 1:
            return 1
        default:
            return 0
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        switch indexPath.section{
        case 0:
            if let cell1 = tableView.dequeueReusableCell(withIdentifier: "Cell1") as? Cell1{
                return cell1
            }
        case 2:
            if let cell4 = tableView.dequeueReusableCell(withIdentifier: "Cell4") as? Cell4{
                return cell4
            }
        case 1:
            if let cellT2 = tableView.dequeueReusableCell(withIdentifier: "Cell2") as? Cell2{
                return cellT2
            }
        default:
            return UITableViewCell()
        }
        
        return UITableViewCell()
        
    }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if indexPath.section == 1 {
            showPopup()
        }else if indexPath.section == 2 {
            self.presenter?.navigatePreguntas()
        }
    }
    func showPopup(){
        let alert = UIAlertController(title: "Continua", message: "Ok", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Tomate una selfie", style: .default, handler: {_ in self.getFoto()}))
        alert.addAction(UIAlertAction(title: "Visualizar la foto", style: .default, handler: {_ in self.getImagen()}))
        alert.addAction(UIAlertAction(title: "Cancelar", style: .destructive, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
    func getFoto() {
        if UIImagePickerController.isSourceTypeAvailable(.camera){
            let imagenPickter: UIImagePickerController = UIImagePickerController()
            imagenPickter.allowsEditing = false
            imagenPickter.sourceType = .photoLibrary
            imagenPickter.delegate = self
            present(imagenPickter, animated: true, completion: nil)
        }
    }
    func getImagen() {
        if UIImagePickerController.isSourceTypeAvailable(.photoLibrary){
            let imagenPickter: UIImagePickerController = UIImagePickerController()
            imagenPickter.allowsEditing = false
            imagenPickter.sourceType = .photoLibrary
            imagenPickter.delegate = self
            present(imagenPickter, animated: true, completion: nil)
        }
    }
}
extension Table3CeldasViewController: UIImagePickerControllerDelegate{
}
