//
//  Table3CeldasInteractor.swift
//  5857Examen iOS
//
//  Created Gerardo on 19/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Table3CeldasInteractor: Table3CeldasInteractorProtocol {

    weak var presenter: Table3CeldasPresenterProtocol?
}
