//
//  Table3CeldasPresenter.swift
//  5857Examen iOS
//
//  Created Gerardo on 19/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class Table3CeldasPresenter: Table3CeldasPresenterProtocol {

    weak private var view: Table3CeldasViewProtocol?
    var interactor: Table3CeldasInteractorProtocol?
    private let router: Table3CeldasWireframeProtocol

    init(interface: Table3CeldasViewProtocol, interactor: Table3CeldasInteractorProtocol?, router: Table3CeldasWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func navigatePreguntas() {
        self.router.navigatePreguntas()
    }
}
