//
//  TablaGraficasViewController.swift
//  5857Examen iOS
//
//  Created Gerardo on 24/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TablaGraficasViewController: UIViewController,TablaGraficasViewProtocol {
    
    @IBOutlet weak var tableView: UITableView!
    var item: [Question] = []
    
	var presenter: TablaGraficasPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(UINib(nibName: "Cell3", bundle: nil), forCellReuseIdentifier: "Cell3")
        tableView.reloadData()
        presenter?.getInfo()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
    }

}
extension TablaGraficasViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return item.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cellT3 = tableView.dequeueReusableCell(withIdentifier: "Cell3") as? Cell3{
            cellT3.descGrafica.text = item[indexPath.row].text
            cellT3.text1.text = item[indexPath.row].chartData[0].text
            cellT3.porcentaje1.text = "\(item[indexPath.row].chartData[0].percetnage)%"
            cellT3.text2.text = item[indexPath.row].chartData[1].text
            cellT3.porcentaje2.text = "\(item[indexPath.row].chartData[1].percetnage)%"
            cellT3.view1.backgroundColor = .blue
            cellT3.view2.backgroundColor = .red
            cellT3.view1.layer.cornerRadius = cellT3.view1.frame.height/2
            cellT3.view2.layer.cornerRadius = cellT3.view2.frame.height/2
            return cellT3
        }
        return UITableViewCell()
    }
    func infoPreguntas(items: [Question] ){
        self.item = items
        tableView.reloadData()
    }
}
