//
//  TablaGraficasPresenter.swift
//  5857Examen iOS
//
//  Created Gerardo on 24/01/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TablaGraficasPresenter: TablaGraficasPresenterProtocol {

    weak private var view: TablaGraficasViewProtocol?
    var interactor: TablaGraficasInteractorProtocol?
    private let router: TablaGraficasWireframeProtocol

    init(interface: TablaGraficasViewProtocol, interactor: TablaGraficasInteractorProtocol?, router: TablaGraficasWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func getInfo(){
        self.interactor?.getInfo()
    }
    func infoPreguntas(items: [Question] ){
        self.view?.infoPreguntas(items: items)
    }

}
